### ISSUE TITLE
Does not build due to the css import

### ISSUE THREAD

**Issue by stahlmanDesign** [bbgrabbag/react-pulser#1]
I followed the same [demo](https://medium.com/@BrodaNoel/how-to-create-a-react-component-and-publish-it-in-npm-668ad7d363ce) you did and built a simple React component like yours. Everything builds fine except if I add `import './index.css'`. If I comment out that line it builds fine and I can publish to npm and import into a project.

I saw that your module imports index.css next to the index.js, just as I am trying to do. You added and the relevant css-loader files to package.json and webpack.config.js. I did everything as you did but when I when I run `npm run build` and then import the module in a project I get these errors:

```
./src/sd-react-loading/build/index.js
  Line 1377:  Unexpected '!' in '!!../node_modules/css-loader/index.js!./styles.css'. Do not use import syntax to configure webpack loaders  import/no-webpack-loader-syntax
  Line 1568:  'DEBUG' is not defined                                                                                                         no-undef
```

So I cloned your repo to see how you got it to work, but I also get a build error with your repo:
```
./src/react-pulser/build/index.js
  Line 228:  'DEBUG' is not defined                                                                                                           no-undef
  Line 685:  Unexpected '!' in '!!../node_modules/css-loader/index.js!./index.css'. Do not use import syntax to configure webpack loaders     import/no-webpack-loader-syntax
  Line 879:  Unexpected '!' in '!!../../node_modules/css-loader/index.js!./index.css'. Do not use import syntax to configure webpack loaders  import/no-webpack-loader-syntax
```

Does it look like I am missing something? Can you get a fresh clone of your project to build?

**Comment by bbgrabbag** [comment]
I cloned my repo, and ran `npm install` and `run build` out of the box and it worked just fine. Are the css loaders installed properly?

**Comment by stahlmanDesign** [comment]
Yes, it does build, but when you import the **built index.js** into a project, it throws those errors. I assumed that meant there's a problem and it's not ready to publish to NPM (but your published module on NPM works fine).

If I set up a simple create-react-app project and try to import the module like this:
`import Pulser from "./react-pulser/build/index.js"`
(where your cloned project is in the cra project at root level) it throws the errors.

If I change the `build` to `src` it works:
`import Pulser from "./react-pulser/src/index.js`
… but then of course that's not the point. I don't want the ES6 code prior to the webpack build, I want to test that the transpiled code works before publishing to NPM.

The point of the whole exercise was to be sure the project I built was safe to publish. But maybe I'm missing something. Maybe the transpiled file is not quite the same as when it's published and imported by adding it to package.json and npm installing it.

**Comment by bbgrabbag** [comment]
Oh I see what you mean. So instead of directly importing the component from `./react-pulser/build/index.js` do the following:

from the module you want to test: `npm link`
from the project you want to import the module: `npm link react-pulser`

now you can simply import the module like normal: `import Pulser from "react-pulser"`

**Comment by stahlmanDesign** [comment]
Excellent, that works! I saw the first `npm link` in the demo, but missed that second link: `npm link react-fancy-component`
I'll read up on `npm link` and `npm unlink`. Looks like it could get confusing...
